!!python/object:ml_collections.config_dict.config_dict.ConfigDict
_convert_dict: true
_fields:
  concepts: demo-data/demo_chartevents_user_1.csv
  data: demo-data/CHARTEVENTS.csv
  kwargs: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      spikes: true
      text_color: Black
      text_font: verdana
      text_size: 12
      title_color: Black
      title_font: verdana
      title_size: 25
    _locked: false
    _type_safe: true
  metadata: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
    _configdict: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
      _convert_dict: true
      _fields:
        labels: &id001 !!python/object:ml_collections.config_dict.config_dict.ConfigDict
          _convert_dict: true
          _fields:
            app: mimic-iv-dash
            version: 2.0
          _locked: false
          _type_safe: true
        name: demo-development
      _locked: false
      _type_safe: true
    _convert_dict: true
    _fields:
      labels: !!python/object:ml_collections.config_dict.config_dict.FrozenConfigDict
        _configdict: *id001
        _convert_dict: true
        _fields:
          app: mimic-iv-dash
          version: 2.0
        _locked: false
        _type_safe: true
      name: demo-development
    _locked: false
    _type_safe: true
  ontology: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      location: ontology
      search: pylucene
    _locked: false
    _type_safe: true
  results: results-json/demo
_locked: false
_type_safe: true
