# This YAML exposes the fields defined in the dashboard. Please edit directly.
directories:
  results: C:\Users\Justin\PycharmProjects\mimic-iv-dash\results-json
  data: C:\Users\Justin\PycharmProjects\mimic-iv-dash\demo-data # observations will be split into a file per measurement
  loinc: C:\Users\Justin\PycharmProjects\mimic-iv-dash\demo-data
graphs: # options for graphs
  pairs: # standard measurements for tab graph overlays       // allow user to choose num of tabs in future
    pair_one:
      item_1: 50821
      item_2: 50818
      label: Blood Gas
    pair_two:
      item_1: 50912
      item_2: 50971
      label: Chemistry
    pair_three:
      item_1: 51222
      item_2: 51300
      label: Complete Blood Count
  kwargs:
    title-font: verdana
    title-color: Black
    title-size: 25
    text-font: verdana
    text-color: Black
    text-size: 12
    height: 375
    spikes: True
version: 2.6
kind: Development
metadata:
  name: mimic-iv-dash-development
  labels:
    app: dash-web
temp:
  test: True
  mimic-iv-version: 2.0

