# This YAML exposes the fields defined in the dashboard. Please edit directly.
directories: # default relative, can set to absolute path
  results: results-json # directory to store .json annotations
  concepts: demo-data # directory to concepts to be annotated
  data: demo-data # directory to patient data (eventually split into 1 file per measurement, labevents for now)
loinc:
  location: demo-data
  version: 2.72
  type: Core
  loinc-class-type-value: 1
  loinc-class-type-label: Laboratory Terms
  related:
    scorer: tf_idf # (partial_ratio, jaro_winkler, tf_idf)
graphs: # options for graphs
  pairs: # standard measurements for tab graph overlays       // eventually allow user to choose num of tabs
    pair_one:
      item_1: 50821
      item_2: 50818
      label: Blood Gas
    pair_two:
      item_1: 50912
      item_2: 50971
      label: Chemistry
    pair_three:
      item_1: 51222
      item_2: 51300
      label: Complete Blood Count
  kwargs:
    title-font: verdana
    title-color: Black
    title-size: 25
    text-font: verdana
    text-color: Black
    text-size: 12
    height: 375
    spikes: True
version: 2.6
kind: Development
metadata:
  name: mimic-iv-dash-development
  labels:
    app: dash-web
temp: # for development
  test: False
  mimic-iv-version: 2.0

