!!python/object:ml_collections.config_dict.config_dict.ConfigDict
_convert_dict: true
_fields:
  directories: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      concepts: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          filename: D_LABITEMS.csv
          location: demo-data
        _locked: false
        _type_safe: true
      data: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          filename: LABEVENTS.csv
          location: demo-data
        _locked: false
        _type_safe: true
      results: results-json
    _locked: false
    _type_safe: true
  graphs: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      kwargs: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          height: 375
          spikes: true
          text_color: Black
          text_font: verdana
          text_size: 12
          title_color: Black
          title_font: verdana
          title_size: 25
        _locked: false
        _type_safe: true
      pairs: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          pair_one: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              item_1: 50821
              item_2: 50818
              label: Blood Gas
            _locked: false
            _type_safe: true
          pair_three: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              item_1: 51222
              item_2: 51300
              label: Complete Blood Count
            _locked: false
            _type_safe: true
          pair_two: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
            _convert_dict: true
            _fields:
              item_1: 50912
              item_2: 50971
              label: Chemistry
            _locked: false
            _type_safe: true
        _locked: false
        _type_safe: true
    _locked: false
    _type_safe: true
  ontology: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      class_label: !!python/object:ml_collections.config_dict.config_dict.FieldReference
        _field_type: &id001 !!python/name:builtins.str ''
        _ops: []
        _required: false
        _value: Laboratory Terms
      class_value: !!python/object:ml_collections.config_dict.config_dict.FieldReference
        _field_type: !!python/name:builtins.int ''
        _ops: []
        _required: false
        _value: 1
      filename: LoincTableCore.csv
      location: demo-data
      name: loinc
      related: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _convert_dict: true
        _fields:
          location: !!python/object:ml_collections.config_dict.config_dict.FieldReference
            _field_type: *id001
            _ops: []
            _required: false
            _value: demo-data
          scorer: tf_idf
        _locked: false
        _type_safe: true
      version: !!python/object:ml_collections.config_dict.config_dict.FieldReference
        _field_type: &id002 !!python/name:builtins.float ''
        _ops: []
        _required: false
        _value: 2.72
    _locked: false
    _type_safe: true
  temp: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      five_percent_dataset: !!python/object:ml_collections.config_dict.config_dict.FieldReference
        _field_type: !!python/name:builtins.bool ''
        _ops: []
        _required: false
        _value: false
      mimic_iv_version: !!python/object:ml_collections.config_dict.config_dict.FieldReference
        _field_type: *id002
        _ops: []
        _required: false
        _value: 2.0
    _locked: false
    _type_safe: true
_locked: false
_type_safe: true
